# -*- coding: utf-8 -*-
"""dictionaries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FA0rG3XWOzPYtNwAMSQJOlE7yn_k6-o
"""

#Lucas Vandenakker
#CS175
#Dictionary

people = {
    "Danny": "New York",
    "Ben": "New Jersey",
    "Bob": "Chicago",
    "Tom": "Houston",
    "Sam": "Pheonix",
    "Tim": "Philadelphia",
    "Nancy": "Chicago",
}

peopleInChicago = [name for name, city in people.items() if city == "Chicago"]

for name in peopleInChicago:
    print(name)

#Lucas Vandenakker
#CS175
#Swapped dictionary

original = {
    "Math": "Alice",
    "Science": "Bob",
    "History": "Charlie",
}

swapped = {subject : person for person, subject in original.items()}

print(swapped)

#Lucas Vandenakker
#CS175
#Nested dictionaries

employees = {
    "Alice" : {"age" : 25, "department" : "Sales"},
    "Bob" : {"age" : 30, "department" : "Marketing"},
    "Charlie" : {"age" : 28, "department" : "Sales"},
    "Daisy" : {"age" : 22, "department" : "IT"},
}

salesOnly = {name : info for name, info in employees.items() if info["department"] == "Sales"}

print(salesOnly)

#Lucas Vandenakker
#CS175
#Nested dictionaries

dict1 = {'a' : 10, 'b' : 20, 'c' : 30}
dict2 = {'b' : 15, 'c' : 5, 'd' : 50}

combined = {}
for name in dict1:
    if name in dict2:
      combined[name] = dict1[name] + dict2[name]
    else:
      combined[name] = dict1[name]

for name in dict2:
    if name not in combined:
      combined[name] = dict2[name]

print(combined)

#Lucas Vandenakker
#CS-175
#Birthdays
birthdays = {}

def getBirthdayAndName():
  name = input("Enter your friends name: ")
  date = input("Enter their birthday in the format MM/DD/YYYY: ")

  birthdays[name] = date

  print(f"{name}'s birthday has been added.")

def displayBirthdays():
  print("Friends birthdays")
  for name, date in birthdays.items():
    print(f"{name}: {date}")

def viewBirthday():
  name = input("Enter the name of the friends birthday you want to view: ")
  print(f"{name}'s birthday is on: {birthdays[name]}")

def mainMenu():
  userIn = 0
  while(userIn != 4):
    print()
    print("Birthday Manager")
    print("1. Add Birthday")
    print("2. View Birthday")
    print("3. Display All Birthdays")
    print("4. Exit")
    userIn = int(input("Enter your choice: "))
    if(userIn == 1):
      getBirthdayAndName()
    elif(userIn == 2):
      viewBirthday()
    elif(userIn == 3):
      displayBirthdays()
    elif(userIn == 4):
      print("Goodbye")
    else:
      print("Invalid choice")


mainMenu()