# -*- coding: utf-8 -*-
"""sets

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1qlAqV2F_7Ze_VulK7GjWhTEa40ZOxg
"""

#Lucas Vandenakker
#CS175
#Sets

baseball = set(['Jodi', 'Carmen', 'Aida', 'Alicia'])
basketball = set(['Eva', 'Carmen', 'Alicia', 'Sarah'])

print("The following students are on the baseball team: ")
for i in baseball:
  print(i)
print()

print("The following students are on the basketball team: ")
for i in basketball:
  print(i)
print()

print("The following students play both basketball and baseball: ")
for i in (baseball & basketball):
    print(i)
print()

print("The following students play both basketball or baseball: ")
for i in (baseball | basketball): #union
  print(i)
print()

print("The following students play baseball but not basketball: ")
for i in (baseball - basketball):
  print(i)
print()

print("The following students play basketball but not baseball: ")
for i in (basketball - baseball):
  print(i)
print()

print("The following students play one sport, but not both: ")
for i in (baseball ^ basketball): #symmertic difference, in either a or b but not ab
  print(i)